sudo: required
services:
  - docker


before_install:
  - docker build -t goilby/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true goilby/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-rest"
  env: "Docker-rest-env"
  bucket_name: "elasticbeanstalk-eu-west-3-785791989909"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  skip_cleanup: true
